# A Dockerfile for a Python image with matplotlib, numpy, and pandas installed

FROM python:3.12.0-alpine

# Install matplotlib, numpy, and pandas
RUN pip install --no-cache-dir matplotlib pandas numpy
